Update pr_checks_backend.yml

diff --git a/.github/workflows/pr_checks_backend.yml b/.github/workflows/pr_checks_backend.yml
--- a/.github/workflows/pr_checks_backend.yml
+++ b/.github/workflows/pr_checks_backend.yml
@@ -4,11 +4,12 @@ on:
   pull_request:
     branches:
       - staging
-    paths:
-      - 'data/**'
-      - 'Dockerfile-pg'
-      - 'init_pg.sql'
-      - 'docker compose.yml'
+      - rmartinsen-patch-1
+    # paths:
+      # - 'data/**'
+      # - 'Dockerfile-pg'
+      # - 'init_pg.sql'
+      # - 'docker compose.yml'
   workflow_dispatch:
 
 jobs:
@@ -29,96 +30,97 @@ jobs:
         with:
           python-version: '3.11.4'
 
-  run-formatter:
-    runs-on: ubuntu-latest
-    needs: setup
-    continue-on-error: true
+  # run-formatter:
+  #   runs-on: ubuntu-latest
+  #   needs: setup
+  #   continue-on-error: true
 
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v4
 
-      - name: Run Ruff Formatter in Docker
-        run: |
-          cd data
-          docker compose run --rm formatter
+  #     - name: Run Ruff Formatter in Docker
+  #       run: |
+  #         cd data
+  #         docker compose run --rm formatter
 
-  run-linter:
-    runs-on: ubuntu-latest
-    needs: setup
-    continue-on-error: true
+  # run-linter:
+  #   runs-on: ubuntu-latest
+  #   needs: setup
+  #   continue-on-error: true
 
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v4
 
-      - name: Run Ruff Linter in Docker
-        run: |
-          cd data
-          docker compose run --rm linter
+  #     - name: Run Ruff Linter in Docker
+  #       run: |
+  #         cd data
+  #         docker compose run --rm linter
 
-  build-project:
-    runs-on: ubuntu-latest
-    needs: setup
+  # build-project:
+  #   runs-on: ubuntu-latest
+  #   needs: setup
 
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v4
 
-      - name: Build vacant-lots-proj
-        run: |
-          cd data
-          docker compose build vacant-lots-proj
+  #     - name: Build vacant-lots-proj
+  #       run: |
+  #         cd data
+  #         docker compose build vacant-lots-proj
 
-  run-services:
-    runs-on: ubuntu-latest
-    needs: build-project
+  # run-services:
+  #   runs-on: ubuntu-latest
+  #   needs: build-project
 
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v4
 
-      - name: Run all services
-        run: |
-          cd data
-          docker compose up -d
+  #     - name: Run all services
+  #       run: |
+  #         cd data
+  #         docker compose up -d
 
-  check-build-status:
-    runs-on: ubuntu-latest
-    needs: run-services
+  # check-build-status:
+  #   runs-on: ubuntu-latest
+  #   needs: run-services
 
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v4
 
-      - name: Check build status
-        if: failure()
-        run: |
-          echo "One or more services failed to build and run."
-          exit 1
-      - name: Report success
-        if: success()
-        run: echo "All services built and ran successfully."
+  #     - name: Check build status
+  #       if: failure()
+  #       run: |
+  #         echo "One or more services failed to build and run."
+  #         exit 1
+  #     - name: Report success
+  #       if: success()
+  #       run: echo "All services built and ran successfully."
 
-  check-lint-format-status:
-    runs-on: ubuntu-latest
-    needs: [run-formatter, run-linter]
+  # check-lint-format-status:
+  #   runs-on: ubuntu-latest
+  #   needs: [run-formatter, run-linter]
 
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v4
 
-      - name: Check formatter and linter status
-        if: failure()
-        run: |
-          echo "Formatting or linting issues found. Please fix the issues."
-          exit 1
-      - name: Formatter and linter success
-        if: success()
-        run: echo "Formatting and linting passed successfully."
+  #     - name: Check formatter and linter status
+  #       if: failure()
+  #       run: |
+  #         echo "Formatting or linting issues found. Please fix the issues."
+  #         exit 1
+  #     - name: Formatter and linter success
+  #       if: success()
+  #       run: echo "Formatting and linting passed successfully."
 
   test:
       runs-on: ubuntu-latest
+      needs: setup
       defaults:
         run:
           working-directory: data/src
